codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "50...70"
  status:
    project:
      default:
        informational: true
        target: auto
        threshold: 1%
    patch:
      default:
        informational: true
        target: 70%

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false